### ISSUE TITLE
Overwritable templates

### ISSUE THREAD

**Issue by lalstef** [ljagis/leaflet-measure#11]
That's a great plugin! There is one thing I would very much like that it supports: custom templates. What about putting  the templates into `options` so we can use our own templates? I think this should be pretty easy, isn't it?

``` javascript
L.Control.Measure = L.Control.extend({
  _className: 'leaflet-control-measure',
  options: {
    position: 'topright',
    primaryLengthUnit: 'feet',

    resultsTemplate = _.template("....")
}
...
```

and then in code

``` javascript
  _updateResults: function () {
    var calced = calc.measure(this._latlngs);

    // instead of : this.$results.innerHTML = resultsTemplate({})
    this.$results.innerHTML = this.options.resultsTemplate({});
```

**Comment by brandoncopeland** [comment]
Thank you for the suggestion. I don't think this is a feature we want to support at this time. There seems to be some interest, so maybe in the future? I would like to keep the control usage simple though, and this would add some complexity.
