### ISSUE TITLE
CSS cannot be loaded

### ISSUE THREAD

**Issue by Rickyc81** [ljagis/leaflet-measure#121]
Hello, I did not understand what are the js and css files to download for my html, if i download leaflet-measure.js and leaflet-measure.scss on my site tells me this:

![istantanea_2018-08-09_18-06-20](https://user-images.githubusercontent.com/4402040/43911133-f2c625e2-9bfe-11e8-8ea4-601d71b7a771.png)

**Comment by Rickyc81** [comment]
Solved, downloaded js and css from the demo site..

**Comment by zhuqiandai** [comment]
thanks
