### ISSUE TITLE
Open measurenet by js call, without user map interaction

### ISSUE THREAD

**Issue by Kulikovpavel** [ljagis/leaflet-measure#13]
Is it possible not to add control, but to open measurement block manually?

**Comment by brandoncopeland** [comment]
Hmmm.. I think the answer is no, not currently, but can you explain a bit more? Do you have any other examples of other Leaflet controls that include the behavior you're looking for?

`calc.js` includes just the calculation logic. `leaflet-measure-template-results.html` and `popuptemplates/*` contain all HTML templates for the results. Maybe these could be used independent of the control if that helps.

**Comment by brandoncopeland** [comment]
Closed due to inactivity
