### ISSUE TITLE
leaflet-measure not working with Leaflet 1.0 beta 2

### ISSUE THREAD

**Issue by DrYSG** [ljagis/leaflet-measure#15]
Tried out this plug-in with Leaflet 1.0.0-beta.2 (99a48a5), but one only gets a dot, it does not create polylines or polygons nor does it report lat/lon.

This might be related to:

https://github.com/Leaflet/Leaflet.draw/issues/455
https://github.com/Leaflet/Leaflet/issues/4018

Windows 7 OS, Chrome Version 46.0.2490.86 m

**Comment by stretchkerr** [comment]
I'm also using leaflet 1.0 beta 2. Leaflet measure plugin works as expected
in chrome on my android tablet and my iPhone 4 (don't laugh), but not in
any browser on any desktop OS I've tried.

**Comment by brandoncopeland** [comment]
Fixed at commit 5f0ead9

The original implementation added a polygon overlay covering the full map to receive clicks and add measure points. This keeps getting in the way, including this issue. Removed completely. Now, new points are added to the measurement with clicks handled on the map directly.

**Comment by brandoncopeland** [comment]
Also.. A new example page using Leaflet 1.0.0 Beta 2 was added
