### ISSUE TITLE
Compatibility with L.mapbox.map

### ISSUE THREAD

**Issue by mgincnj** [ljagis/leaflet-measure#2]
Love the plugin!  However, I'm building a map using mapbox extensions (e.g. L.mapbox.map), and my code hiccups if I try to add leaflet-measure.  Change L.mapbox.map to L.map, and measure works (though on my maps, a lot of other stuff breaks).  Any chance of supporting mapbox?

**Comment by brandoncopeland** [comment]
Can you describe your code hiccups?

Everything seems ok for me with both

```javascript
L.mapbox.accessToken = 'sometoken';
L.mapbox.map('map', 'examples.map-i86nkdio', {
  measureControl: true
});
```
and
```javascript
L.mapbox.accessToken = 'sometoken';
L.mapbox.map('map', 'examples.map-i86nkdio');
var measureControl = L.control.measure();
measureControl.addTo(map);
```

**Comment by mgincnj** [comment]
Hey Brandon!  I was using an earlier version of Mapbox (1.6.x), mostly because it doesn't require the Access Token and I'm not using mapbox hosting (I'm generating my own mbtiles files, and using a local server).  I do have an account and a token, and when I linked to your suggested release, it started to work!

I'm very excited as I think it will add a lot to my application!  I presume there are no issues with doing that... my "free" account isn't going to expire.

**Comment by brandoncopeland** [comment]
Great! I believe the token associated with your account should be fine for what you are doing, but you may want to double check with Mapbox. I'm happy our control can help you out.
