### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by regmebaby** [ljagis/leaflet-measure#20]
The demo does not work.

```
TypeError: d is undefined
d.Control.Measure=d.Control.extend({_className:"leaflet-control-measure",options...
leaflet....min.js (Zeile 3, Spalte 1)

TypeError: L is undefined
var map = L.map('map', {
/leaflet-measure/ (Zeile 51, Spalte 9)
```

Maybe a result of the JS Minification...

**Comment by brandoncopeland** [comment]
Have you also included Leaflet?

```html
<!doctype HTML>
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css">
  <link rel="stylesheet" href="leaflet-measure.css">
</head>
<body>
  <script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
  <script src="leaflet-measure.min.js"></script>
  <script>
    // Start creating maps
  </script>
</body>
</html>
```

**Comment by brandoncopeland** [comment]
I'm sorry. Guess I didn't read that very well. You said the demo. I'll check into it.

**Comment by regmebaby** [comment]
@brandoncopeland http://ljagis.github.io/leaflet-measure :-)

**Comment by brandoncopeland** [comment]
I don't see an issue there in OSX Chrome. What browser are you using?

**Comment by regmebaby** [comment]
In Firefox 43.0.3 it does **not** work.

Just tested with Chrome: works

Strange...

**Comment by regmebaby** [comment]
![issue1](https://cloud.githubusercontent.com/assets/8546924/12095361/656ea06a-b30e-11e5-8812-3dcb38d4742b.JPG)
![issue2](https://cloud.githubusercontent.com/assets/8546924/12095365/6716834c-b30e-11e5-8880-2b153ece5059.JPG)

**Comment by brandoncopeland** [comment]
Are you loading the page over HTTPS (https://ljagis.github.io/leaflet-measure)?

The Leaflet CDN resources locations are HTTP. Requesting across protocols (HTTP from HTTPS page) could trigger FF to abort the request.

**Comment by regmebaby** [comment]
Yes. I deactivated [HTTPS Everywhere](https://addons.mozilla.org/de/firefox/addon/https-everywhere/) and now it works.Thank you!

**Comment by regmebaby** [comment]
Demo uses `<script src="//cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>`
-->  autodetect HTTP / HTTPS
manual access of that URL brings `ssl_error_bad_cert_domain`

![issue3](https://cloud.githubusercontent.com/assets/8546924/12098521/2bc1e182-b323-11e5-9882-11865be0f1bc.JPG)

So it is a problem of the Leaflet CDN

**Comment by brandoncopeland** [comment]
Great! Thanks for reporting. This is fixed this in the examples by explicitly requesting HTTP, but is not yet published to the demo.
