### ISSUE TITLE
leaflet measure for angular

### ISSUE THREAD

**Issue by badreal** [ljagis/leaflet-measure#23]
Is there a way to integrate the plugin with angular leaflet directive ?

I tried to use the custom controls like this :

    var measureControl = new L.Control.Measure({
            position: 'left'
        });

    angular.extend($scope, {
         controls : {
              custom : [measureControl]
         }
     })

    <leaflet center="center" controls="controls" layers="layers"></leaflet>

But it doesn't work.

**Comment by badreal** [comment]
After debugging, I figured out that i was wrong, the position left doesn't exist. Closing the issue.

**Comment by ekiziltas** [comment]
Hi badreal,

How did you achieve to integrate measure capability to angularjs as a custom add-on. As far as I try, I have faced an error that is definitely made me crazy. It says, when I try to use as you did, ` Cannot read property 'addTo' of undefined".

Regards

**Comment by RatebSAYAH** [comment]
Hello @badreal ,
After adding import "leaflet-measure"; in component, i have this error :²
Property 'Measure' does not exist on type 'typeof Control'
Did you get this type of error?

**Comment by konstanddp** [comment]
@RatebSAYAH, struggling with the same issue. did you manage to get around it?

**Comment by RatebSAYAH** [comment]
@konstanddp yes, you had to add a typing file.

1. Create a folder and inside a typing file within /src. (example : /src/typing/leaflet-measure.d.ts)
2. Content of the typing file : 
`
  import * as L from 'leaflet';
  declare class MeasControl extends L.Control {}
  declare module 'leaflet' {
  namespace Map {
  export interface MapOptions {
      measureControl?: boolean;
    }
  }
  export interface ControlStatic {
    Measure: Control.MeasureStatic;
  }
  namespace Control {
    export interface MeasureStatic {
      new (options?: IMeasureConstructorOptions): Measure;
    }
  export interface IMeasureConstructorOptions {
      position?: string;

      parentContainerSelector?: string;

      primaryLengthUnit?: string;

      secondaryLengthUnit?: string;

      secondaryAreaUnit?: string;

      primaryAreaUnit?: string;

      activeColor?: string;

      completedColor?: string;

      popupOptions?: IMeasurePopupOptionsOptions;

      captureZIndex?: number;

      localization?: string;

      decPoint?: string;

      thousandsSep?: string;
    }
    export interface IMeasurePopupOptionsOptions {
      className?: string;
      autoPanPadding?: Array<number>;
    }
    type Measure = MeasControl;
    let Measure: typeof MeasControl
    //export interface Measure typeof MeasControl
  }

    export namespace control {
     export function measure(
      options?: Control.IMeasureConstructorOptions
     ): Control.Measure;
   }
  }
`
3. Add in your tsconfig.app.json : "files": [ "typing/leaflet-measure.d.ts"]

**Comment by konstanddp** [comment]
@RatebSAYAH thank you, that helped a lot!
do you possibly know why the icon looks like this? the popup on clicking it also incorrectly formatted, but the rest is fine
![image](https://user-images.githubusercontent.com/60286456/211671234-a03fcf63-6ea0-44b0-99f1-3a4812667f28.png)

**Comment by RatebSAYAH** [comment]
@konstanddp please add to your angular.js :
"styles": ["node_modules/leaflet-measure/dist/leaflet-measure.css"]

**Comment by konstanddp** [comment]
thanks a lot, I had it in, turns out my app required a restart :-D

**Comment by harshharsha** [comment]
Hello @RatebSAYAH I have added file as you mentioned above but still getting this error
Uncaught ReferenceError: __dirname is not defined
    at leaflet-measure.js:12:50
any solution for this?

I'm using leaflet verion 1.9.4 and leaflet-measure 1.2.0

**Comment by RatebSAYAH** [comment]
@harshharsha Install leaflet-measure@^3.1.0
