### ISSUE TITLE
events : start , end.

### ISSUE THREAD

**Issue by badreal** [ljagis/leaflet-measure#24]
Is there any events like measure start or end ?

**Comment by brandoncopeland** [comment]
There currently is not. This is a good suggestion.

**Comment by brandoncopeland** [comment]
I like this suggestion, but I think we need a few use cases to best design these events.

We could add 2 simple events - `measurestart` and `measureend`. Neither would include any additional data. They would fire when the user clicks "Create a new measurement" and when a measurement is completed by either user doubleclick or user clicking  "Finish measurement", respectively.

I see potential use of an additional event fired on each new point added/measurement calculated. Something like "measureupdate" with data including raw values of the measurement (area, length, last coordinate). The complexity with this is that all measurements are maintained as meters/sqmeters internally, so exposing this data through an event means it may not match the units specified with the various units options of the control.

@badreal How do would anticipate using the measure start/end events?

**Comment by badreal** [comment]
For my use case , i needed measurestart and measureend to disable layers click listener to have the possibility to add points on existing layer by simulating a map click.
Another use case is to toggle layers as measure event starts/ends.
That gives lot of opportunities.
As very advanced usage, one could set a maximum area and measureupdate would be used to calculate the area and compare it with max one.

**Comment by DavidZebris** [comment]
I've also got the problem, that my map-click-listener always gets active when I'm clicking into the map to do a measurement. That opens a popup for every click..

If I had events like "measure-start" and "measure-stop" it would be easy to disable the normal map-click-listener for that time.

I'm still searching for a workaround, but haven't found something yet.

**Comment by brandoncopeland** [comment]
While start/end events will be useful, it sounds like the real problem is Issue #25. I think resolving that issue will be a priority.

**Comment by brandoncopeland** [comment]
While `measurestart` and `measureend` have been suggested a few times, it seems the reason is always to disable click events on other map markers. I'm not opposed to adding these events, but I am leaning towards adding a solution to avoid click events on other map layers while a measure is active. Just do this by default (with maybe an option to disable) instead of requiring everyone to add some implementation inside of these events.

Regardless, this issue seems to be affecting a few people. I'll make an effort to add a fix within the next week or so.

**Comment by DrYSG** [comment]
From a UI/HumanFactors viewpoint, and from watching users, I would agree. Measurement is pretty much a single mode of workflow, and you want a "dead" map when taking measurements, not live things popping up or happening.

**Comment by brandoncopeland** [comment]
I would still like to add this feature to disable/avoid other click events (issue #37). In the meantime, I went ahead and merged the alternative `measurestart`, `measureend` events at commit 2a383db.
