### ISSUE TITLE
Does'nt work in webpack

### ISSUE THREAD

**Issue by somsub** [ljagis/leaflet-measure#30]
npm install leaflet-measure
var L = require('leaflet');
require('leaflet-measure');

Complains of fs..
Error:
webpackMissingModule	@	leaflet-measure.js:14
(anonymous function)	@	leaflet-measure.js:14
(anonymous function)	@	leaflet-measure.js:407
(anonymous function)	@	bundle.js:5325
__webpack_require__	@	bundle.js:30
(anonymous function)	@	Map.jsx:31
(anonymous function)	@	bundle.js:5127
__webpack_require__	@	bundle.js:30
(anonymous function)	@	TraitMap.jsx:29
(anonymous function)	@	bundle.js:5115
__webpack_require__	@	bundle.js:30
(anonymous function)	@	TraitMapContainer.jsx:33
(anonymous function)	@	bundle.js:3681
__webpack_require__	@	bundle.js:30
(anonymous function)	@	MainContentContainer.jsx:25
(anonymous function)	@	bundle.js:3675
__webpack_require__	@	bundle.js:30
(anonymous function)	@	AppContainer.jsx:35
(anonymous function)	@	bundle.js:3441
__webpack_require__	@	bundle.js:30
(anonymous function)	@	app.js:45
(anonymous function)	@	bundle.js:57
__webpack_require__	@	bundle.js:30
(anonymous function)	@	bundle.js:50
(anonymous function)	@	bundle.js:53
webpackUniversalModuleDefinition	@	bundle.js:7
(anonymous function)	@	bundle.js:10

**Comment by TigleyM** [comment]
Ran into this problem too. You need to add the following to webpack.config.js:


```
node: {
  fs: 'empty',
}
```

And under module.loaders: 

`{ test: /leaflet-measure.+\.js$/,loader: 'transform/cacheable?brfs'}`

**Comment by somsub** [comment]
You rock!!! Thanks
