### ISSUE TITLE
Measurement to Map Markers (with popup)

### ISSUE THREAD

**Issue by DrYSG** [ljagis/leaflet-measure#36]
I have lots of MapMarkers with bound popups (click) that give details about that sensor reading. Users love the leaflet-measure tool. But the issue is that they cannot take measurements of distances between  map markers due to the conflict of what .click() does. 

Any suggestions?

**Comment by brandoncopeland** [comment]
Thanks. I think this is the same as Issues #24 and #25. This seems to be an issue for multiple users and something we'll tackle very soon (next week or so).
