### ISSUE TITLE
Get the results

### ISSUE THREAD

**Issue by ekiziltas** [ljagis/leaflet-measure#39]
Hi, is there any way to get the result values? As far as I examine the "measurefinish" event, it is just used for warning the user. By the way I don't want to get the values from DOM search, after popup appears.

Regards

**Comment by brandoncopeland** [comment]
I've added an example of the results data at http://ljagis.github.io/leaflet-measure/

**Comment by ekiziltas** [comment]
I am so happy with that, many thanks :)
