### ISSUE TITLE
Docking with zoom controls

### ISSUE THREAD

**Issue by alexcroox** [ljagis/leaflet-measure#4]
I would love to add this into the single control panel I currently have with zoom and [fullscreen](https://github.com/brunob/leaflet.fullscreen) buttons.

![ss](http://al3x.me/aeK0/d)

Is there an option to combine or does it have to sit standalone?

**Comment by brandoncopeland** [comment]
Sorry. I'm not aware of any built in feature with Leaflet to do this.

This control extends [L.Control](http://leafletjs.com/reference.html#control), similar to the `Layers` control. Ideally, I think, you could create a "Control Bar" that would allow you to dock any number of `L.Control` items. I haven't seen a plugin or anything for that yet though.
