### ISSUE TITLE
Reduce size

### ISSUE THREAD

**Issue by brandoncopeland** [ljagis/leaflet-measure#44]
leaflet-measure.min.js is relatively large. Work to reduce this size. An easy start is to decide if some of the little used dependencies (like `color`) are worth the overhead.

**Comment by rjdestigter** [comment]
A bit part of it's size is it's dependency on i18n. I wonder if the package `convert-units` would be a better option if that applied

**Comment by brandoncopeland** [comment]
Size has been significantly reduced as of version 3.0.0. 36KB or so now.
