### ISSUE TITLE
Demo page broken

### ISSUE THREAD

**Issue by neothemachine** [ljagis/leaflet-measure#5]
Tested with latest Firefox.

**Comment by brandoncopeland** [comment]
What are you seeing? Looks ok to me on OSX, Firefox 39.0.

**Comment by neothemachine** [comment]
Sorry, my HTTPS Everywhere browser extension loaded the https version, which in turn fails: https://ljagis.github.io/leaflet-measure/ You may close the issue if you want.

**Comment by brandoncopeland** [comment]
Thanks for spotting. The demo has been updated to support https.

**Comment by neothemachine** [comment]
Unfortunately this is only half the soluton :) The leafletcdn https endpoint has an invalid ssl certificate which means that browsers will still not load the demo. But don't worry, I mentioned this elsewhere and I think the cdn should be fixed.

**Comment by brandoncopeland** [comment]
Gotcha. Thanks
