### ISSUE TITLE
Three points and it works?

### ISSUE THREAD

**Issue by DrYSG** [ljagis/leaflet-measure#50]
Very odd issue with new version. I am using Chrome v51. The first measurement I try to make, The First click (no lat/lon) Second No lat/lon, third, then I get a three point measurement. (using latest beta of Leaflet). 

But then if I cancel or accept the measurement, and start making new measurements, I get correct operation from the very first point (first: lat/long, second click: a line measurement, etc.)

```
             measureControl = new L.Control.Measure({
                 position: 'topleft',
                 captureZIndex: 10000,
                 primaryLengthUnit: 'meters',
                 secondaryLengthUnit: 'cm',
                 primaryAreaUnit: 'sqmeters',
                 secondaryAreaUnit: 'sqm',
                 units: {
                     cm: {
                         factor: 100,
                         display: 'cm',
                         decimals: 2
                     },
                     sqm: {
                         factor: 1,
                         display: 'sqm',
                         decimals: 4
                     }
                 }
             });

```

**Comment by brandoncopeland** [comment]
There was an issue with how i18n was used. Fixed at v 2.0.1.

http://codepen.io/brandoncopeland/full/WxxGNo/
