### ISSUE TITLE
Leaflet loaded twice with webpack

### ISSUE THREAD

**Issue by turban** [ljagis/leaflet-measure#58]
leaflet-measure.js includes: 

var L = require('leaflet');

https://github.com/ljagis/leaflet-measure/blob/master/src/leaflet-measure.js#L4

For most use cases Leaflet will already be loaded, which means Leaflet is loaded twice and overrides the already loaded version (which causes problems in my case).

**Comment by Ralf8686** [comment]
Just need remove leaflet from dependencies and add to devDependencies

**Comment by er1x** [comment]
Same problem with Browserify here. It conflicts with my previous Leaflet instance, in my case v1.x and other plugins do not work.
