### ISSUE TITLE
Tools doesn't work after I add my layers to the map?

### ISSUE THREAD

**Issue by dodriscoll** [ljagis/leaflet-measure#6]
Hi There,
This is a great tool and is exactly what I'm looking for but unfortunately I can't get it to work!  It works fine when I add it to a map with just some generic baselayers but I have an image map service that is brought in using l.esri.imageMapService and then rendered using a raster function.  

My image layer is in WGS 1984 Web Mercator Auxillary Sphere.  Any advice would be greatly appreciated.

Thanks

**Comment by brandoncopeland** [comment]
Can you provide a simple example to reproduce the issue?

**Comment by mikefedak** [comment]
I am have the same issue. It seems that the map service image overlays the polygon leaflet measure uses to collect results.

**Comment by dodriscoll** [comment]
Actually I have it working now.  I'm not 100% sure what fixed it as I've been doing other stuff and then thought I'd just give it another go before the next set of testing. Possibly the main change since I last tried it is  I upgraded to the new leaflet and new esri-leaflet libraries and this resolved the issue?

My image layers are called using the esri-leaflet plugin and it seemed to be only when I brought in the image layers that I have the problem so my best guess is they've made a change that was required.

It works anyway and that's the main thing! Thanks

**Comment by mikefedak** [comment]
dodriscoll, what versions of esri-leaflet and leaflet are you using?

**Comment by dodriscoll** [comment]
Now using esri-leaflet-v-2.0.0-beta.5 and leaflet-1.0.0-b1.

**Comment by mikefedak** [comment]
Ok thanks, Unfortunately I have other dependencies that prevent me from upgrading.

**Comment by dodriscoll** [comment]
Before I got this measure tool working again I did configure the draw tool to show the measurements as tool tip when drawing a line or an area.  This worked before I upgraded if that would be any use.

**Comment by mikefedak** [comment]
Thanks, however I think I have a workaround; if I call bringToBack(); on the esri-leaflet layer it seems. to work.
