### ISSUE TITLE
Error when building with webpack

### ISSUE THREAD

**Issue by turban** [ljagis/leaflet-measure#67]
When I try to include leaflet-measure as a dependency and build with webpack I get this error: 

ERROR in .../leaflet-measure/dist/leaflet-measure.js
Module build failed: SyntaxError: Invalid number (4006:32)

> 4006 | 			fs.mkdirSync(this.directory, 0755);

It seems like this is non-standard way of writing an octal number - it should be:

fs.mkdirSync(this.directory, 0o755);

See options defaults here:
https://nodejs.org/api/fs.html#fs_fs_createwritestream_path_options

**Comment by brandoncopeland** [comment]
Thanks. This will be resolved when issue #70 is implemented. Closed in favor of that issue.
