### ISSUE TITLE
does not work with create-react-app

### ISSUE THREAD

**Issue by barbalex** [ljagis/leaflet-measure#68]
Steps to recreate:

Create a new app:

    npm install -g create-react-app
    create-react-app my-app
    cd my-app
    npm start

works.

Install leaflet and leaflet-measure:

    npm i --save leaflet leaflet-measure

Import into `my-app/src/App.js`:

    import 'leaflet'
    import 'leaflet-measure'

See this error in the console:

    leaflet-measure.js:15Uncaught TypeError: fs.readFileSync is not a function
        at Object.<anonymous> (leaflet-measure.js:15)
        at Object.<anonymous> (leaflet-measure.js:457)
        at __webpack_require__ (bootstrap 056f279…:555)
        at fn (bootstrap 056f279…:86)
        at Object.<anonymous> (App.js:6)
        at __webpack_require__ (bootstrap 056f279…:555)
        at fn (bootstrap 056f279…:86)
        at Object.<anonymous> (index.js:3)
        at __webpack_require__ (bootstrap 056f279…:555)
        at fn (bootstrap 056f279…:86)
    (anonymous) @ leaflet-measure.js:15
    (anonymous) @ leaflet-measure.js:457
    __webpack_require__ @ bootstrap 056f279…:555
    fn @ bootstrap 056f279…:86
    (anonymous) @ App.js:6
    __webpack_require__ @ bootstrap 056f279…:555
    fn @ bootstrap 056f279…:86
    (anonymous) @ index.js:3
    __webpack_require__ @ bootstrap 056f279…:555
    fn @ bootstrap 056f279…:86
    (anonymous) @ bootstrap 056f279…:578
    __webpack_require__ @ bootstrap 056f279…:555
    (anonymous) @ bootstrap 056f279…:578
    (anonymous) @ bootstrap 056f279…:578

May be related to https://github.com/ljagis/leaflet-measure/issues/30 and https://github.com/ljagis/leaflet-measure/issues/67

**Comment by barbalex** [comment]
Hm. Nodes `fs` function is used here: https://github.com/ljagis/leaflet-measure/blob/master/src/leaflet-measure.js#L15-L19

This is quite obviously not going to work in a browser.

**Comment by barbalex** [comment]
For the meantime I can circumvent the problem by importing like this:

    import '../../../../node_modules/leaflet-measure/dist/leaflet-measure'

instead of:

    import 'leaflet-measure'

**Comment by barbalex** [comment]
Thanks for this great tool!

**Comment by brandoncopeland** [comment]
This control is built with Browserify and intended to be used from the `dist` directory. It has been this way since originally built in 2015.

I would like to update the build to webpack but have not yet had the opportunity. Until then, importing from `dist` is probably the best solution.

**Comment by brandoncopeland** [comment]
Closed in favor of issue #70
