### ISSUE TITLE
Migrate build from Grunt/Browserify to Webpack

### ISSUE THREAD

**Issue by brandoncopeland** [ljagis/leaflet-measure#70]

**Comment by reptillicus** [comment]
I could be persuaded to work on this, but I can't get to it until Mid June probably.

**Comment by SylvainCorlay** [comment]
I stumbled upon this as I am working on integrating `leaflet-measure` to the `ipyleaflet` jupyter widget. Is there any workaround?

**Comment by brandoncopeland** [comment]
This has been needed for a while. I haven't had much opportunity to look into it, but I will make an effort to make some progress this week.

**Comment by brandoncopeland** [comment]
This is done as of release 3.0.0

**Comment by SylvainCorlay** [comment]
Great thanks @brandoncopeland
