### ISSUE TITLE
resultFeature.getBounds is not a function - single point doubleclick with current version of Leaflet (1.03) 

### ISSUE THREAD

**Issue by seahik** [ljagis/leaflet-measure#73]
When using leaflet-measure plugin with current version of Leaflet - 1.03

Below error occurs when double-clicking on one point.   Prevents popup for point location from showing.

`Uncaught TypeError: resultFeature.getBounds is not a function`
`line 7361  leaflet-measure.js`

**Comment by marigerr** [comment]
From Leaflet changelog [1.0-beta1 (July 14, 2015)](https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md#10-beta1-july-14-2015)

> * Changed Circle to inherit from CircleMarker and not the other way.

CircleMarker no longer inherits from from Circle which has the getBounds() method.

**Comment by brandoncopeland** [comment]
Thanks for catching this
