### ISSUE TITLE
When using `preferCavas`, measure tool is broken

### ISSUE THREAD

**Issue by reptillicus** [ljagis/leaflet-measure#78]
If using a canvas renderer for leaflet, the measurement tool is somewhat broken. The control points dont show up and there is an error stating `layer._path` is undefined. Is there some way to support the canvas renderer or trick the map into using svg renderer for measurement drawing? 

[Link to plunker](https://plnkr.co/edit/wcIR3Aehrpo8c54fZOpd?p=preview)

**Comment by s-chand** [comment]
Yes it is. I think this is more a leaflet implementation issue than a measure tool one.

However, it'll be a nice to have for canvas based leaflet maps on the measure tool
