### ISSUE TITLE
Clicking on map after starting measurement not doing anything

### ISSUE THREAD

**Issue by Alloc86** [ljagis/leaflet-measure#8]
Hi there,

just added the measure control to my map (after trying it on your demo and now I really want it ;) ). The control itself works fine: It enlarges when hovering, I can start measurements and cancel / "finish" them. But after starting a measurement clicking on the map does not add any points.

Stripped my stuff from the code so it's now basically just a Leaflet map instance with the control added, still not working. You can have a look at it here: http://illy.bz/tmp/measure-test/ (or download that test on http://illy.bz/tmp/measure-test.7z ).

Any idea what's going wrong with my map?

Kind regards,
Chris

**Comment by brandoncopeland** [comment]
When a measure is started, a polygon is added to the map at coordinates `[[90, -180], [90, 180], [-90, 180], [-90, -180]]` (https://github.com/ljagis/leaflet-measure/blob/master/src/leaflet-measure.js#L146). Click events on this polygon will add points/vertexes to the measure geometry. Initially, this proved more reliable in some situations than listening to click events on the map.

In your example, adding the polygon at the coordinates `[[90, -180], [90, 180], [-90, 180], [-90, -180]]` doesn't cover the full map. The polygon is aqua shaded area below. Measurements would be performed in this area.
![image](https://cloud.githubusercontent.com/assets/1182714/9120321/41b1ea54-3c41-11e5-90a8-ea92eb202ae4.png)

I suspect this is related to your custom `crs` defined in the map options. We'll need to look into the best method of adding the polygon to ensure full map coverage in this situation.. Or reevaluate if adding this polygon to collect click events is necessary.

**Comment by Alloc86** [comment]
Is there a way to query Leaflet for it's current screen bounds? So you know what coordinates you'd have to put the polygon on?
Drawback would probably be though that in this case you would have to disable zoom and pan as long as measurement is active as this would again move the poly out of the view (or listen for those events and update the poly).
What were the problems with map.on(click)?

**Comment by stretchkerr** [comment]
I have the same issue - I can start a new measurement, but cannot add any points to the map. I works fine on my tablet (Chrome on Samsung Tab S 10.1), but does not work on my laptop. I'm wondering if it has something to do with enabling scrolling on touch devices on the https://github.com/davicustodio/Leaflet.StyledLayerControl plugin, by adding this code:

if (!L.Browser.touch) {
      L.DomEvent
      .disableClickPropagation(control._container)
      .disableScrollPropagation(control._container);
      } else {
      L.DomEvent.disableClickPropagation(control._container);
      }

       L.control.scale().addTo(map);	

My page here: https://dl.dropboxusercontent.com/u/7075784/Leaflet/Leaflet2.html

**Comment by brandoncopeland** [comment]
Fixed at 5f0ead9.

When a measure is started, click events directly on the map are now used to add new measure points. The extra polygon overlay to collect click events was removed completely.

**Comment by Alloc86** [comment]
Thanks, working as expected :)
