### ISSUE TITLE
Assigning the measure control event to a html Button and use from there?

### ISSUE THREAD

**Issue by nagasreev** [ljagis/leaflet-measure#80]
Hi, 
At present, the measure control is added to Map. I dont want the control get added to my map. Instead i had a html toolbar and on click of a button inside that, the measure control event should activate. 

Leaflet.PM (drawing tool plugin) gave the option to assign the events to custom buttons. Is it possible with your plugin. Please help.

**Comment by nagasreev** [comment]
- [ ]

**Comment by Gbacc** [comment]
I guess it is not possible.
I had to make changes in this plugin to make it work like passing the accessor in the options

```js
let options = {
            parentContainerSelector: 'my-navbuttons .boxDraggableContent'
        };
        let measureControl = L.control.measure(options);
        measureControl.addTo(this._mapLeafletService.map);
```

And parsing this option in the plugin. (I extended it for all leaflet controls)

```js
L.Control = L.Control.extend({
    addTo: function(map){
      this.remove();
		this._map = map;

    if(this.options.parentContainerSelector){
      this._parentContainer = $(this.options.parentContainerSelector);
    }

		var container = this._container = this.onAdd(map),
		    pos = this.getPosition(),
		    corner = map._controlCorners[pos];

		L.DomUtil.addClass(container, 'leaflet-control');

    if(this._parentContainer){
      this._parentContainer.appendChild(container);
    } else {
      if (pos.indexOf('bottom') !== -1) {
        corner.insertBefore(container, corner.firstChild);
      } else {
        corner.appendChild(container);
      }
    }
		
		return this;
}
});
```

Now the container is accessible in the plugin 

```js
 _initLayout: function () {
var parentContainer = this._parentContainer;
...
$start = $('.js-start', parentContainer) || $('.js-start', container);
...
}
```

**Comment by micahwilhelm** [comment]
Even with these modifications, I'm still sure how to use this answer. 
@nagasrreev could you please post the code that you used to assign the event to a button?

**Comment by micahwilhelm** [comment]
@nagasreev 
Even with these modifications, I'm still sure how to use this answer. 
Could you please post the code that you used to assign the event to a button?
