### ISSUE TITLE
Allow setting options from map options

### ISSUE THREAD

**Issue by mhasbie** [ljagis/leaflet-measure#82]
Hi,
Appreciate it if you could allow setting of leaflet-measure options from map options during map initialization.

In leaflet-measure.js from line 7480:

```javascript
L.Map.mergeOptions({
  measureControl: false,
  measureControlOptions: null
});

L.Map.addInitHook(function () {
  if (this.options.measureControl) {
    this.measureControl = (new L.Control.Measure(this.options.measureControlOptions)).addTo(this);
  }
});
```

**Edit:**
Then we can do this:

```javascript
var myMap = L.map('mapElementId', {
  measureControl: true,
  measureControlOptions: options
});
```

Much appreciated if we can have this feature.
Thank you.

**Comment by brandoncopeland** [comment]
If passing options is required, you can create a new instance of the control and add to the map. I think this is the typical practice. I would like to follow the standards set by other community controls where possible. Do any other controls include this feature? If it is a common practice, we can certainly reopen. Thanks.
