### ISSUE TITLE
Webpack compile error upon import

### ISSUE THREAD

**Issue by annelorraineuy** [ljagis/leaflet-measure#84]
One of the dependencies of this package is causing a Webpack compile error which comes out simply by importing leaflet-measure. 

Screenshot: 
<img src="https://user-images.githubusercontent.com/5892190/28944310-627711cc-785f-11e7-8d91-f8a0c720024c.png" width=582 />

**Here is the PR for the fix:** https://github.com/ljagis/leaflet-measure/pull/83

**Comment by StuRuby** [comment]
I met the same question,have you resloved it ?

**Comment by brandoncopeland** [comment]
I think this is resolved as of release 3.0.2. Please confirm.
