### ISSUE TITLE
Matching Standard Control Style

### ISSUE THREAD

**Issue by sdlime** [ljagis/leaflet-measure#92]
When placing the measure control in the context of standard zoom/full-screen controls (e.g. position:topleft) you really notice the styling difference between the measure toggle button and the others. Is there a way to match the styling? Adding the leaflet-bar class to the leaflet-control-measure div seems to help visually (size needs tweaking) although it hoses up the interaction div links. I'm guessing that's fixable.

Perhaps that could be an option?

--Steve

**Comment by sdlime** [comment]
In case anyone is watching I was able to get things matching using a couple of local styles and jquery.

Styles:
  .leaflet-control-measure-toggle { width: 30px !important; height: 30px !important; }
  .leaflet-control-measure .tasks a { width:auto; height:auto; text-align:left; display:inline; }

Javascript:
  $(".leaflet-control-measure").addClass("leaflet-bar");

![sample](https://user-images.githubusercontent.com/1599227/36166966-d5ba445e-10b9-11e8-8541-ea382ec47fed.png)

**Comment by brandoncopeland** [comment]
I think this is fixed with release 3.0.2. Please take a look to confirm.

I originally matched the control styles to the layers control provided by Leaflet. I can see how that control was a bit different and mimicking the `leaflet-bar` is a better option.
